version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: magnus
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    image: maven:3.9-eclipse-temurin-17
    command: ./mvnw -DskipTests spring-boot:run
    working_dir: /workspace
    volumes:
      - ./magnus-backend:/workspace
      - ~/.m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/magnus?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./magnus-frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./magnus-frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

