package com.magnus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaskDependencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskDependencyAllPropertiesEquals(TaskDependency expected, TaskDependency actual) {
        assertTaskDependencyAutoGeneratedPropertiesEquals(expected, actual);
        assertTaskDependencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskDependencyAllUpdatablePropertiesEquals(TaskDependency expected, TaskDependency actual) {
        assertTaskDependencyUpdatableFieldsEquals(expected, actual);
        assertTaskDependencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskDependencyAutoGeneratedPropertiesEquals(TaskDependency expected, TaskDependency actual) {
        assertThat(actual)
            .as("Verify TaskDependency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskDependencyUpdatableFieldsEquals(TaskDependency expected, TaskDependency actual) {
        assertThat(actual)
            .as("Verify TaskDependency relevant properties")
            .satisfies(a -> assertThat(a.getDependencyType()).as("check dependencyType").isEqualTo(expected.getDependencyType()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskDependencyUpdatableRelationshipsEquals(TaskDependency expected, TaskDependency actual) {
        assertThat(actual)
            .as("Verify TaskDependency relationships")
            .satisfies(a -> assertThat(a.getPrerequisiteTask()).as("check prerequisiteTask").isEqualTo(expected.getPrerequisiteTask()))
            .satisfies(a -> assertThat(a.getDependentTask()).as("check dependentTask").isEqualTo(expected.getDependentTask()));
    }
}
