apiVersion: apps/v1
kind: Deployment
metadata:
  name: magnus-frontend
  namespace: magnus
  labels:
    app: magnus-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magnus-frontend
  template:
    metadata:
      labels:
        app: magnus-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: magnus-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: magnus-config
              key: vite-api-url
        - name: VITE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: magnus-config
              key: vite-environment
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: magnus-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: magnus-frontend
  namespace: magnus
  labels:
    app: magnus-frontend
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: magnus-frontend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: magnus-frontend-hpa
  namespace: magnus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magnus-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80