name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magnus
          MYSQL_USER: magnus
          MYSQL_PASSWORD: magnus
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17
  - name: Make mvnw executable
    working-directory: magnus-backend
    run: chmod +x mvnw
  - name: Build (skip tests)
    working-directory: magnus-backend
    run: ./mvnw -B -DskipTests -T1C package

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: magnus-frontend/package-lock.json
      - name: Install
        working-directory: magnus-frontend
        run: npm ci
      - name: Build
        working-directory: magnus-frontend
        run: npm run build

